name: pixel_snap_generator
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0-444.0.dev <3.0.0"

dependencies:
   args: ^2.3.1
   analyzer: ^5.2.0
   dart_style: ^2.2.4
   collection: ^1.17.0
   path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
