on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  Flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - name: Flutter Format
        run: flutter format . --output=none --set-exit-if-changed
      - name: Install Melos
        run: flutter pub global activate melos
      - name: Melos Boostrap
        run: melos bootstrap
      - name: Flutter Format
        run: melos exec -c 1 flutter format . --output=none --set-exit-if-changed
      - name: Flutter Analyze
        run: melos exec -c 1 flutter analyze
      - name: Futter Test
        run: melos exec -c 1 flutter test
