on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  Flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - name: Flutter Format
        run: flutter format . --output=none --set-exit-if-changed
      - name: Flutter Analyze
        run: flutter analyze
      - name: Futter Test
        run: flutter test
